### ISSUE TITLE
Fatal could not read from remote repository

### ISSUE THREAD

**Issue by levlup1** [Larpon/ingrid#1]
Authenticity of host, can't be established. Attached fatal command prompt 
[ReadMe.txt](https://github.com/Larpon/ingrid/files/13244121/ReadMe.txt)

**Comment by larpon** [comment]
Try checking your github access and ssh settings. If you're not a github user try just git clone via https:
`git clone https://github.com/Larpon/ingrid`

**Comment by levlup1** [comment]
> Try checking your github access and ssh settings. If you're not a github user try just git clone via https: `git clone https://github.com/Larpon/ingrid`

I ran the following :
git config -l

it returned 

user.name=levlup1
user.email=levlup1@gmail.com

I keep going through rabbit holes. Quick question, is there anything that you learned when working with computers that if you would have learned earlier would have saved you more time and be more productive? If so give me a tip and a hint! Thanks

**Comment by larpon** [comment]
> Quick question, is there anything that you learned when working with computers that if you would have learned earlier would have saved you more time and be more productive?

That's unfortunately not quick for me to answer since there's too much to sum up from all the experience I've gained through the past ~25 years and most would probably be subjective. 

A few *major* thing I do think I benefitted from learning :
* when I switched from using Windows to using Linux.
* learning to be friends with the commandline and terminal
* when I started coding in V for my own projects - my productivity sky rocketed

**Comment by larpon** [comment]
This thread is not private, by the way

**Comment by levlup1** [comment]
> This thread is not private, by the way

thank you I was able to fix my ash key I appreciate your help!
